version: '3'

services:
  translator-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    environment:
      - PORT=5000
    restart: unless-stopped

volumes:
  huggingface-cache: 